M48
; DRILL file KiCad 10.0.6-10.0.6~ubuntu26.04.1 date 2026-09-29T06:23:19
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-29T06:23:19+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6-10.0.6~ubuntu26.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.100
%
G90
G05
T1
X140.5Y-97.0
X140.5Y-113.0
X155.5Y-97.0
X156.5Y-113.0
M30
